"""Added OTP verification columns

Revision ID: 8d4274bedbc0
Revises: 831011663b79
Create Date: 2026-04-08 20:56:20.769651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4274bedbc0'
down_revision: Union[str, Sequence[str], None] = '831011663b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user_table', sa.Column('otp', sa.String(length=6), nullable=True))
    op.add_column('user_table', sa.Column('otp_exp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user_tasks', 'user_table', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_column('user_table', 'otp_exp')
    op.drop_column('user_table', 'otp')
    op.drop_column('user_table', 'is_verified')
    # ### end Alembic commands ###
